### ISSUE TITLE
RFM69 id and group resets to i0 and g210

### ISSUE THREAD

**Issue by rob570** [Open-Building-Management/emontx_sniffer#1]
Hi,
I've a custom id and group for the RFM69 tx/rx. Don't understand why, at every boot I've to manually set the id and group to my configuration (id:15 and group:200) using ssh debugging and minicom.
Could someone help me to solve?
Many thanks!

**Comment by alexandrecuer** [comment]
Hello 
What do you use, the receiver attached to gpio or an usb key ? You use the sniffer as an home assistant addon or with plain docker or an orchestration tool like portainer ?

**Comment by alexandrecuer** [comment]
This tool is very basic. I'm not that familiar with the jeelib format and sure it should be improved. Anyway it just reads the serial port and if "OK" is found, it tries to organize a MQTT payload :
https://github.com/Open-Building-Management/emontx_sniffer/blob/7fe0dd0c704367b14b5fa2547fdff482e5b08475/jeelib_sniffer.py#L110

**Comment by rob570** [comment]
Hi Alex,
I have an old RFM12pi (the one with ATMega, like in your documentation) connected to GPIO. I use the sniffer as an hass addon, so to modify the config I had to enable ssh debuggind and run your docker image.
I've solved adding a conf parameter and send it after the serial init.
It's rude but now it works!
Thank you for your code!


`RFM69_CONF = "15i 200g\n"
if VERBOSITY:
    log.setLevel("DEBUG")
else:
    log.setLevel("INFO")
info_message = f'MQTT_HOST : {MQTT_HOST} - MQTT_PORT : {MQTT_PORT}'
log.info(info_message)

def connect_to_serial(port, baudrate):
    """open a serial socket"""
    try:
        socket = serial.Serial(port, baudrate, timeout=0)
    except (ValueError, serial.SerialException) as err:
        error_message = f'error {err}'
        log.error(error_message)
        return None
    socket.write(RFM69_CONF.encode('utf-8'))
    success_message = f'connected to {port}@{baudrate}'
    conf_message=f'Sent configuration:{RFM69_CONF}'
    log.debug(conf_message)
    log.debug(success_message)
    return socket`

**Comment by alexandrecuer** [comment]
Nice job, I think i made tests with the RFM69 only, not the RFM12

I've seen your mods on your fork. Maybe we should consider integrate them in the repo, what do you think ?

The thing should be to add in the config.yaml some options like a SEND_CONFIG boolean set by default to false and a CONFIG_STR string set by default to your conf, so one can do or not all that job from the UI...

https://github.com/Open-Building-Management/emontx_sniffer/compare/main...rob570:emontx_sniffer:main

just a question, why do you use your custom id and group ? security ?

**Comment by alexandrecuer** [comment]
Anyway, i thought that once you write to the rfm and save, you dont have you do it again...but maybe it is not the case with rfm12?

**Comment by alexandrecuer** [comment]
@rob570 : for the venv, i think you dont have to activate at startup, cf the `CMD` part of the dockerfile... You can just add this :
```
#!/ve/bin/python3
```
in the sniffer.py file

**Comment by alexandrecuer** [comment]
> added topic customization (I would like to push data on HASS, avoiding emoncms addon)

Thats makes sense. Topic customization is a good addition. You want to use the mqtt broker addon and not the emoncms addon, isn'it ? You plan to use grafana or is hass storage enough for you ?

By the way, do you know there is an emonhub addon ?
https://hub.docker.com/r/alexjunk/emonhub

**Comment by rob570** [comment]
...
> 
> By the way, do you know there is an emonhub addon ? https://hub.docker.com/r/alexjunk/emonhub

Uh Doh! I didn't!
Anyway my Pi i s overloaded (I should buy the coral TPU for frigate) and another container could take it down.
To use you emonhub I should only create the config yaml isn't it? I'll try.
About the topic customization you're right, I would like to use the mqtt broker addon.
The warning raised after the build of my docker image is about the format on the RUN command, it is not a json array. Don't know why it works without enabling the venv, but it does.

**Comment by alexandrecuer** [comment]
> To use you emonhub I should only create the config yaml isn't it? I'll try.

Yes. At least. A .devcontainer folder should help and will save your time so you can test everything with vscode...cf https://github.com/Open-Building-Management/emoncms


> The warning raised after the build of my docker image is about the format on the CMD command

Do you build locally ? Or use github actions as a pipeline ? With a recent version of docker, you should have no warning...

**Comment by rob570** [comment]
...
> Do you build locally ? Or use github actions as a pipeline ? With a recent version of docker, you should have no warning...

I've built with:
` docker buildx build --platform linux/arm/v7 -t rob570/emontx_sniffer:alpine3.21.2 https://github.com/rob570/emontx_sniffer.git`

and the output was:
`1 warning found (use docker --debug to expand):
 - JSONArgsRecommended: JSON arguments recommended for CMD to prevent unintended behavior related to OS signals (line 14)`

**Comment by alexandrecuer** [comment]
Did you test to build and run with the previous CMD ["python3", "jeelib_sniffer.py"]

with the `#!/ve/bin/python3`
at the top of the sniffer.py file

**Comment by rob570** [comment]
Sorry I apologize for what I've written in a previous post. I had to activate the venv, that's why I've merged two command in the CMD line your syntax didn't work with my venv.

**Comment by alexandrecuer** [comment]
You dont have to a activate the venv. 

Forget what i've said with the # shebang and check this :

https://github.com/Open-Building-Management/containers/blob/7d2c71d99d5ae3f0f2b7cc9d3c83c743427ca0c7/emonhub/Dockerfile#L59

If you do this, the path will know that you want to run the python version from the venv

**Comment by rob570** [comment]
> You just have to add your CMD command after this ENV command

Yes, it works! Thank you!

**Comment by alexandrecuer** [comment]
perfect, what you can do to clean the code is also to remove the activate you have when installing the libs.

add some ARGS at the top of your dockerfile, ARGS are only for build time, whereas ENV can be for both, but more intended to run time : 
```
ARG \
    ENV_DIR=/ve \
```
then your RUN command becomes something like :
```
        python3 -m $ENV_DIR;\
 	$ENV_DIR/bin pip install --no-cache-dir pyserial paho-mqtt requests
```
it is much cleaner and you dont have to use activate

**Comment by alexandrecuer** [comment]
![Image](https://github.com/user-attachments/assets/fd92fa3d-75a8-4f61-acf1-35b309538e3f)

your mods are consolidated in the venv branch
if you want to try, just add this url to the addon repositories store : 
https://github.com/Open-Building-Management/emontx_sniffer#venv

could be nice if you could give some details on your use case, how you deal with data coming into the mqtt broker

tested on my side with an usb key but did not make usage of the write_to_rfm69

![Image](https://github.com/user-attachments/assets/d5ed1d70-302e-4263-a544-b7a34670da23)

**Comment by rob570** [comment]
Wonderful!
I can confirm that everything works fine. I can close the fork on my git.
About my use case I would like to use the readings as sensors input, but I've a lot to test and learn on sensors configurations.
I tried to add this to hass configuration.yaml but it doesn't work.
Thank you!

```
mqtt:
  sensor:
  - name: "Inported/Exported Power"
    state_topic: "emon/6"
    unit_of_measurement: 'W'
    value_template: "{{ value_json.1}}"
    unique_id: IEPower
```

**Comment by alexandrecuer** [comment]
I will add the timezone in the config
I saw you made a mod on that but forgot to include

For mqtt i wrote some things but it is the opposite you want to achieve, ie data from home assistant to emoncms....
https://github.com/Open-Building-Management/emoncms/discussions/16

The mqtt broker addon does not manage on its own to report data received as home assistant states ? I thought that no yaml is actually needed...

**Comment by rob570** [comment]
> The mqtt broker addon does not manage on its own to report data received as home assistant states ? I thought that no yaml is actually needed...

I've understood that if the topic is'nt hass formatted then autodiscover doesn't work.
So I've tried to define mqtt sensors.
[https://community.home-assistant.io/t/how-do-i-create-mqtt-sensor/398370/12](url)

**Comment by alexandrecuer** [comment]
Not sure doing this with yaml is the right way. It will be hard to maintain. And you will not benefit of unique ids in home assistant for your sensors....

**Comment by rob570** [comment]
> Not sure doing this with yaml is the right way. It will be hard to maintain. And you will not benefit of unique ids in home assistant for your sensors....

I think there's a misunderstanding: I'm referring to HASS configuration.yaml, not the emontx_sniffer one.
Here it is a portion of the relevant part. Now it works, and I'm able to read negative values too

```
mqtt:                                                                                                                                                     
  sensor:  
    - name: "Solar Power"                                                                                                                           
      state_topic: "emon/6"                                                                                                                        
      device_class: power                                                                                                                          
      state_class: measurement                                                                                                                     
      unit_of_measurement: 'W'                                                                                                                     
      value_template: >                                                                                                                            
        {% if value_json['2'] > 30000 %}                                                                                                           
          {{ value_json['2'] - 65535 }}                                                                                                            
        {% else %}                                                                                                                                 
          {{ value_json['2'] }}                                                                                                                    
        {% endif %}                                                                                                                                
      unique_id: "SolarPower"                                                                                                                      
      icon: mdi:solar-panel        
    - name: "TBoiler"                                                                                                                                     
      state_topic: "emon/6"                                                                                                                               
      device_class: temperature                                                                                                                           
      state_class: measurement                                                                                                                            
      unit_of_measurement: 'C'                                                                                                                            
      value_template: "{{ value_json['8']/10|round(1)}}"                                                                                                  
      unique_id: TBoiler  
```
